#!/bin/bash
# SVK Blueprint - Icon Generator Helper
# This script creates placeholder icons for PWA

# Colors
ACCENT="#ffd700"  # Gold
BG="#0a0a0a"      # Dark

echo "📱 SVK Blueprint - Icon Setup"
echo "=============================="
echo ""
echo "You need to create app icons for the PWA to work properly."
echo ""
echo "REQUIRED ICON SIZES:"
echo "  - icon-72.png   (72x72)"
echo "  - icon-96.png   (96x96)"
echo "  - icon-128.png  (128x128)"
echo "  - icon-144.png  (144x144)"
echo "  - icon-152.png  (152x152)"
echo "  - icon-192.png  (192x192) ← REQUIRED FOR PWA"
echo "  - icon-384.png  (384x384)"
echo "  - icon-512.png  (512x512) ← REQUIRED FOR PWA"
echo ""
echo "EASY OPTION:"
echo "  1. Go to https://realfavicongenerator.net/"
echo "  2. Upload a single 512x512 image of your logo"
echo "  3. Download the generated icons"
echo "  4. Place them in the 'icons/' directory"
echo ""
echo "MANUAL OPTION (using ImageMagick):"
echo "  If you have ImageMagick installed, run:"
echo ""
echo "  # Create icons directory"
echo "  mkdir -p icons"
echo ""
echo "  # Generate icons from a source image (replace 'logo.png')"
echo "  convert logo.png -resize 72x72 icons/icon-72.png"
echo "  convert logo.png -resize 96x96 icons/icon-96.png"
echo "  convert logo.png -resize 128x128 icons/icon-128.png"
echo "  convert logo.png -resize 144x144 icons/icon-144.png"
echo "  convert logo.png -resize 152x152 icons/icon-152.png"
echo "  convert logo.png -resize 192x192 icons/icon-192.png"
echo "  convert logo.png -resize 384x384 icons/icon-384.png"
echo "  convert logo.png -resize 512x512 icons/icon-512.png"
echo ""
echo "QUICK TEXT-BASED ICONS (SVG → PNG):"
echo "  You can also create simple text-based icons using online tools:"
echo "  - https://www.favicon-generator.org/"
echo "  - https://www.favicongenerator.com/"
echo ""
echo "DEFAULT DESIGN SUGGESTION:"
echo "  - Background: Dark (#0a0a0a)"
echo "  - Icon: Gold 'SVK' text or blueprint symbol (#ffd700)"
echo "  - Round corners for iOS compatibility"
echo ""
echo "Once icons are created, place them in the 'icons/' directory"
echo "next to index.html and the app will automatically use them."
echo ""
